### ISSUE TITLE
Browserify usage

### ISSUE THREAD

**Issue by brettz9** [treojs/idb-schema#4]
I'm sorry for a kind of support question, but is there some easy way to browserify the es6 modules syntax without setting up a grunt file, etc.

**Comment by brettz9** [comment]
One other quick, on-off question: if I enhance your schema objects with methods named `open`, `delete`, and `cmp`, do you expect I might run into any conflict problems with your method names in the future? I think it would be most convenient for me to allow the user to chain `idb-schema` commands into the other db.js commands as opposed to requiring the user to build their own `idb-schema` object and supply it as an option or something.

**Comment by alekseykulikov** [comment]
Hey, I've just published idb-schema@3.0.0 to npm. ES6 is compiled with babel, so you can easily use it with browserify.

**Comment by alekseykulikov** [comment]
For second comment, I don't think, that `idb-schema` should depend on any library semantic, it's just a way to describe `onupgradeneeded` callback. If you wish, you can extend it with different methods, but it will be a different library.

**Comment by brettz9** [comment]
Thanks re: browserify.

Re: method extension, sure...I am just asking about whether my extending it for my own library will possibly run into conflicts with your library later if I you ever decide to use those 3 method names.

**Comment by alekseykulikov** [comment]
Well, I can't say for sure, but 3.x definitely won't. Feel free to rely on current implementation using semver's `^3.0.0` and you will be safe ;)
