### ISSUE TITLE
Method for JSON export of data?

### ISSUE THREAD

**Issue by brettz9** [treojs/idb-schema#6]
I know this is idb _schema_ after all, but what do you think of allowing JSON export of data along with the schema? It certainly seems like a reusable feature...

(Beyond JSON alone, the "structured cloning algorithm" can allow for other types of data which could be reasonably cloned too, but if you're amenable to the feature request, I think JSON would be a nice start...)

Thanks!

**Comment by alekseykulikov** [comment]
Hey! It sounds, like an interesting idea.

Treo internally has [idb-descriptor module](https://github.com/treojs/treo/blob/0.6.0/src/idb-descriptor.js) which allows to extract JSON information from any IndexedDB. I'm going to extract it to separate module someday. Yes, idb-schema is for managing migrations and I would keep it that focuces. It has `schema.stores()` method, which returns the whole structure. Would be nice to sync formats between `schema.stores()` (which also can be renamed to `toJSON()` and `idb-descriptor`.

You idea might be done as a separate module with more features:

``` js
import idbExport from 'idb-export'
import { open } from 'idb-factory'

const db = await open('mydb')
idbExport(db, customExportOptions) // { store1: [], store2: [{...}, {...}], ... }
```

**Comment by brettz9** [comment]
Yeah, that sounds like it'd be a good approach...Thanks!

**Comment by alekseykulikov** [comment]
Btw, if you are willing to implement idb-export, we could add it to treojs family with the same linting & testing infrastructure.

**Comment by brettz9** [comment]
I might. I will probably need this functionality a bit down the road, so may add when I get to it. You want me to reopen here to track?

**Comment by alekseykulikov** [comment]
No need to reopen, just keep this option in mind ;)
