### ISSUE TITLE
Allowing customization of argument(s) passed to `addCallback` callback

### ISSUE THREAD

**Issue by brettz9** [treojs/idb-schema#7]
I've been working on adding `idb-schema` to `db.js` and have it working and passing our tests, but with a slightly ugly user-facing workaround. With an added API to `idb-schema`, the need for this workaround can be avoided and I think may be useful to other libraries.

The issue is that when `callback` is used to build the `upgradeneeded` callback, the callbacks added earlier by `addCallback` will be called with the `upgradeneeded` event, but I'd like to pass our own object as the first argument to allow the user to make db.js-style queries rather than forcing the user to be required to utilize the `upgradeneeded` event.

Would you be open to a PR which supports a callback argument supplied to the `Schema` constructor (perhaps on an options object instead or as a method called directly after Schema()) which, if present, will itself be passed the `upgradeneeded` event and the user's callback so that wrapper can determine what to supply to the user's callback?

User code:

``` js
const schema = new Schema(function (e, cb) {
    cb(dbJSWrapper(e), e);
}).version(1)
  .addStore('books')
  .addCallback((dbJSObject, e) => {
    // do something custom
  })
```

In the db.js code:

``` js
request.onupgradeneeded = e => {
    const idbschema = new IdbSchema();
    userOptions.schemaBuilder(idbschema); // Allow the db.js user to build their schema with `addCallback()`, etc.

    idbschema.callback()(dbJSObject, e); // Pass our own custom object for making db.js queries
};
```

**Comment by alekseykulikov** [comment]
Hey,
Why do you want to wrap `e` in constructor? Maybe, just make a high-order function to do this:

``` js
const schema = new Schema()
.addStore('books')
.addCallback(dbJSWrapper((dbJSObject, e) => {  
})
```

**Comment by brettz9** [comment]
Because I'm exposing the result of new Schema() directly to users and don't want to force them to do the wrapping themselves if they choose to use this feature. I guess I could supply our users with a `Proxy` instead of directly giving them the immediate result of `new Schema`, but I just figured that since this library is intended to be consumed by libraries, and also since it would be ideal for the syntax to work similarly across implementations, that tweaking the argument(s) supplied to the callback(s) be allowed.

**Comment by alekseykulikov** [comment]
>  it would be ideal for the syntax to work similarly across implementations

completely agree!
Maybe, monkey-patching can help?)
Just replace [addCallback](https://github.com/treojs/idb-schema/blob/master/src/index.js#L165) with your own implementation.

**Comment by brettz9** [comment]
Yeah, that was my idea with `Proxy` (though on further thought I really just need to monkey patch the resulting schema object) nor any need to make a full Adapter class. I guess I can do that. Thanks.

**Comment by brettz9** [comment]
Since `callback` was too large to monkey-patch so as to have its call to user callbacks include a second argument, with our dbjs object, I instead, as you suggested, monkey-patched `addCallback`:

``` js
const _addCallback = idbschema.addCallback;
idbschema.addCallback = function (cb) {
    function newCb (e) {
        cb(e, idbschema._dbjs_server);
    }
    return _addCallback.call(idbschema, newCb);
};
```

and then set the pseudo-private `_dbjs_server` with our custom object:

``` js
request.onupgradeneeded = e => {
    const s = dbjs.open(e, ........);
    idbschema._dbjs_server = s;
    idbschema.callback()(e);
};
```

It's a little inelegant but works. However, without an official mechanism for doing this, I'm just concerned that if you later add a second argument when calling the callbacks supplied to `addCallback` then existing code will break.

**Comment by brettz9** [comment]
Upon further contemplation, I see the problem is not merely about passing a promise-supporting API to the callback(s) (and ideally allowing compatibility across idb-schema-utilizing implementations in how callbacks work--i.e., allowing for multiple arguments not through fragile monkey-patching), but also avoiding problems if those callbacks chain promises which do not finish executing before the `upgradeneeded` transaction expires.

I would therefore suggest allowing `request` to be supplied as an argument to the idb-schema constructor or, perhaps better yet, add an `open` method to idb-schema, and have this `open` method create a sequence of `indexedDB.open` requests which synchronously execute already utilized data supplied to `addStore`, etc., but, in the case of callbacks added by `addCallback`, instead of synchronously executing them for each supplied schema version (as in the current `callback()` implementation), we could utilize each `open` call's `request.onsuccess` (where it is safe to chain promises) to first execute any callback(s) added by addCallback() for a given version (duck-typing to see whether a Promise was returned by the user so we can wait until it if finished), and then make a new `open` call to the next higher version in the schema and repeat the steps until all updates are made for all versions, at which time we could then resolve with the highest `open` request result or `success` event.

**Comment by brettz9** [comment]
I intend to prepare a PR now with an `upgrade` method (more descriptive than `open` I think, though we probably want an option to keep the latest version's connection open so as to avoid the user having to repeat this). If you are amenable to this, would you be open to me adding `idb-factory` as a dependency?

**Comment by brettz9** [comment]
And people could still use `callback` if they didn't have promises or other asynchronicity within `addCallback`... (though with this planned `upgrade` API, I intend to only set up new connections if a promise is returned by an `addCallback` callback)

**Comment by brettz9** [comment]
I guess I can work around the original issue, and I've added in a PR my more recent suggestions for adding open/upgrade methods, so I'm closing this issue. Thanks...
