### ISSUE TITLE
Accept array of functions to addCallback

### ISSUE THREAD

**Issue by brettz9** [treojs/idb-schema#8]
Because of the problem with transactions within `upgradeneeded` expiring, if exposing one's library's promise-based API (mentioned in #7), these promises can break within that context, so a workaround may be to send multiple `addCallback` calls, and it would be nice to have a little syntactic sugar to do this more elegantly.

**Comment by brettz9** [comment]
Though the other methods could conceivably benefit (in appearance only) from accepting arrays too...

**Comment by alekseykulikov** [comment]
Maybe use idb-batch with multiple stores support (https://github.com/treojs/idb-batch/issues/1) to avoid this limitation?

**Comment by brettz9** [comment]
`addCallback` would be independent of store though, unless you were talking about accepting an array of callbacks as the third argument there which were not scoped to a particular store:

``` js
await batch(db, {
  magazines: [
    { type: 'add', key: 1, value: { name: 'M1', frequency: 12 } },
    { type: 'add', key: 2, value: { name: 'M2', frequency: 24 } }
  ]
}, [
    function (e) {
        var queryReq = indexedDB.open(db);
        // Add code here, e.g., to modify the store content, rather than schema
    },
    function (e) {
        var queryReq = indexedDB.open(db);
        // Add different code here, e.g., to retrieve store content and based on its result, modify another store's content
    }])
```

**Comment by alekseykulikov** [comment]
It seems, current version of addCallback allows to do this.

``` js
new Schema()
.addCallback((e) => {
  fn1(e)
  fn2(e)
  fn3(e)
})
```

Is it just a matter of API sugar or I don't get it?

**Comment by brettz9** [comment]
Yeah, you're right. :) I had been thinking that since promises wouldn't work within a function in this context, it somehow escaped me that what you mentioned could be done. Thanks!
