### ISSUE TITLE
JSON-based schema-building formats

### ISSUE THREAD

**Issue by brettz9** [treojs/idb-schema#9]
Hi,

Sorry for the long post, but I thought this may interest you.

I'm planning on submitting a PR to add support in db.js for additional JSON-based schema-building formats in addition to the type supported now.

I was wondering whether you were interested in seeing the proposals below added into `idb-schema`. An advantage of this is that we could allow users to more easily mix and match formats, e.g., if they built the first two versions programmatically using idb-schema's current approach but then moved to a simpler JSON-based format or vice versa. Or multiple formats could perhaps even be combined within a single version. Each has its advantages and disadvantages.

The programmatic approach is unique in offering the full expressivity of `addCallback`, while the JSON formats can benefit from being declarative and potentially more succinct.

The first JSON type is already available in db.js (though I want to see it keyed to version so that an extended migration path is possible, e.g., if the user was on version 1 but needed to be brought through versions 2 and 3 as supported in idb-schema).

``` js
{
    store1: {
        key: {keyPath: 'id', autoIncrement: true},
        indexes: {
            firstName: {},
            answer: {unique: true}
        }
    }
}
```

To expand this for supporting versions would be a simple matter of allowing:

``` js
{
    1: {
        store1: {
        // ...
    },
    2: {
        store2: {}
    }
}
```

For each new version, we can compare the stores on the supplied object with the existing stores in the database, and if not in use, we can (optionally) delete them, whereas if there is a change, we can delete unused or changed indexes and create new ones, or rebuild any `keyPath`/`autoIncrement` changes. (This is mostly how it works now.)

The advantage of this approach over the other approaches is that it will show the whole schema in code exactly as it will be built upon each version. The disadvantage is the same (that it will become unwieldy with many versions) and also that it doesn't have a means of indicating that a store should be renamed or copied (though I guess it could be expanded to add `movedFrom` or `copiedFrom` properties). It might also be enhanced to act similarly to JSON Merge Patch (see below) to allow use of `null` to explicitly indicate that a given store, store feature, or index was to be deleted, and otherwise not delete. If we supported both of these changes, then I think the third type below would also automatically be supported as a subset of this (modified) first type.

Maybe we could even allow callbacks here too to get all the capabilities in one (though it would no longer by JSON):

``` js
{
    1: [function myCallback (upgradeneededEvent, librarySpecificObject) {}, {
        store1: {
        }
    ]
```

And/or we might allow `add`/`put`/`delete`/`clear` (with optional keys (including MongoDB-style) where relevant) (as well as an equivalent JSON for our `query` syntax) within the syntax to avoid the need for callbacks (similar to your `idb-batch` format).

The second type is one I wish to add based on [JSON Patch](http://tools.ietf.org/html/rfc6902) though it is based on the first type.

``` js
3: [
     { "op": "remove", "path": "store2" },
     { "op": "add", "path": "store1/indexes", "value": { "lastName": { } } },
     { "op": "replace", "path": "store1/indexes/answer/unique", "value": false },
     { "op": "move", "from": "storeOldName", "path": "storeNewName" },
     { "op": "copy", "from": "people/indexes", "path": "otherPeople/indexes" }
]
```

The advantage here is that besides being declarative, a standard, and only needing to express changes, is that it can indicate the renaming of a store (i.e., `move`) so as to indicate that the original content should be preserved (though under a different name). It can also allow declarative copying (e.g., to replicate indexes on another store).

The third type is [JSON Merge Patch](https://tools.ietf.org/html/rfc7396) (Note that this spec doesn't work well if the `null` value is needed in the altered JSON, but for our `schema` purposes, there are no current arguments which act in a special manner with `null`). 

This approach would also be declarative, a standard, and only need to express changes (including being explicit about whether it was deleting or altering), but it would not allow renaming (or copying) of stores. Its advantage over JSON Patch would be that it is more succinct. Here is the equivalent (minus the `move`/`copy`)

``` js
3: {
    "store2": null,
    "store1": {
        "indexes": {
            "lastName": { }
        },
        "answer": {
            "unique": false
        }
}
```

What do you think?

**Comment by brettz9** [comment]
Btw, regardless of the choice(s) of schema format, I think it would be convenient if your `schema.stores()` format could also be supplied for import and possibly for diffs also.

**Comment by alekseykulikov** [comment]
This is a long post!
I think support of JSON schema is out of scope for this library. If you're willing to implement it, you can create `idb-json-schema` which consumes programmatic approach of `idb-schema`.
But I definitely want to improve format of `schema.stores()` in 4.0 and make it the same as treo's `idb-descriptor`.
